[package]
name = "iced_pfs"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/SkymanOne/IcedPFS"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.4", features = ["pure"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }